# TODO: install limelight https://github.com/koekeishiya/limelight
# actually, do not install limelight
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "jabenninghoff/edge"
# tap "hudochenkov/sshpass"
brew "brew-cask-completion"
# brew "ccze"
brew "cowsay"
brew "eza"  # exa is deprecated https://github.com/eza-community/eza
brew "fd"
brew "fortune"
brew "fping"
brew "fzf"
# brew "git-credential-manager"
brew "gnupg"
brew "htop"
brew "jo"
brew "jq"
brew "macos-trash"
brew "neovim"
brew "pidof"
brew "pylint"
brew "ranger"
brew "ripgrep"
brew "sshpass"
brew "subversion"
brew "tmux"
brew "util-linux"
brew "vifm"
brew "vivid"
brew "jabenninghoff/edge/apg"
# brew "avibrazil-rdm"  # no longer available
# brew "intel-power-gadget"  # not on m1
brew "zsh-completions"  # see instructions for installing
brew "zsh-lovers"  # reference card
brew "bat"
brew "bat-extras"
brew "watch"
brew "hwatch"
brew "dasht"
brew "walk"  # terminal file navigator
brew "rust"
brew "go"
brew "nvm"  # see installation instructions
brew "shellcheck"
# brew "bash-language-server"  # I think :Mason handles this
# cask "displays"  # costs money, not sure yet
cask "aerial"
cask "alacritty"
cask "font-bitstream-vera-sans-mono-nerd-font"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-fira-code"
cask "font-fira-mono-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-juliamono"
cask "font-liberation-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "dash"
