punkte
======
:description: notes on dotfiles in ~/.punkte
:compat-mode!:
:max-width: 100%
:nofooter:
:!version-label:
:listing-caption: Listing
:source-highlighter: pygments


== punkte

=== Backround info:

I learned about using GIT-DIR and WORK-DIR for dotfiles from:

* https://stackoverflow.com/a/16811212/1698426
* https://news.ycombinator.com/item?id=25564555, the whole thread is about dotfiles
* https://www.atlassian.com/git/tutorials/dotfiles
* https://news.opensuse.org/2020/03/27/Manage-dotfiles-with-Git/
* probably not a good idea to run this on the Turris Omnia, but on openwrt I needed to install git, git-http
* https://the.exa.website/docs/colour-themes[exa colours reference]
* `exa` has been abandoned, but there is a better tool called https://eza.rocks[`eza`]


=== On a new installation, I usually want:

[source,zsh,linenums]
----
# git clone https://github.com/marmalodak/home ~/.punkte # switch to using ssh on github
git clone git@github.com:marmalodak/home.git ~/.punkte
git -C $HOME/.punkte/.git --git-dir=$HOME/.punkte/.git --work-tree=$HOME checkout -- $HOME
# open a new shell, then:
punkt reset --hard  # when re-installing dotfiles into a messed up $HOME
# punkt pull --rebase --recurse-submodules --verbose --stat
punkt-auf
oh-my-posh init # untested; p10k deprecated
----

Before being able to push:

[source,ini,linenums]
----
    [user]
        name = John Schmitt
        email = marmalodak@gmail.com
----

==== To Do

. Delete p10k submodule, use a different module as an example below
. do not care about asciio any more
. document install asciidoctor-diagram et al
. the vim macro to convert asciidoc to html should not always try to use Safari, maybe use the OS default
.. e.g. use `open` on macOS and `xdg-open` everywhere else?


==== Trouble

YTF is there a colon in the path to `zsh-edit`? The URL should be `url = https://github.com/marlonrichert/zsh-edit.git`, not `url = https://github.com:marlonrichert/zsh-edit.git`. How did that happen?

NB: submodules need to be absolute paths relative to $HOME

.submodule example
[source,git,linenums]
----
    [submodule ".vim/pack/vim8/start/vim-tmux-pilot"]
        path = .vim/pack/vim8/start/vim-tmux-pilot
        url = https://github.com/urbainvaes/vim-tmux-pilot
----

When `punkt-auf` fails because a submodule will not update because it wants to rebase (WHY???)

For example, `powerlevel10k`:

.P10K has been deprecated, but...
....
rm -rf .powerlevel10k
punkt-aufbau
punkt pull --rebase --recurse-submodules --verbose --stat
....

When `punkt-auf` fails because a submodule cannot be found in .gitmodules:
....
punkt rm --cached .vim/pack/vim8/start/vim-plugin-AnsiEsc
....

=== oh-my-zsh https://github.com/ohmyzsh/ohmyzsh[source]

`ohmyzsh` is a git submodule.

Open a new terminal to invoke the punkte (née dotfiles)

See also `punkt-neu()` in .zshrc


== Brew

`brew bundle install Brewfile`
which was created from `brew bundle dump`

fonts require `svn`


=== rvm https://rvm.io/rvm/install[source]

[NOTE]
----
The RVM installer is beautiful bash code, going to read it and improve my shell game
----

[source,shell,linenums]
----
rvm install "ruby-2.7.8
rvm use ruby-2.7 --default
rvm install asciidoctor-diagram
----

I had trouble installing ruby on my m2 mbp

[source,shell,linenums]
----
rvm install ruby-3.3.0 --with-openss-dir=$(brew --prefix openssl@3)
----

.These are required for `asciio`
[source,shell,linenums]
----
brew install glib
brew install cairo
brew install gtk+
brew install gtk+3 gtk4 gtkextra pango
----

Might be time to give up on drawing in asciidoctor or vim and use PlantUML, graphviz, pikchr

=== apg
`apg` is a great password generator.

. https://github.com/wilx/apg
. https://github.com/jabenninghoff/apg
. https://github.com/jabenninghoff/homebrew-edge

=== brew tap-info

https://stackoverflow.com/questions/25334787/homebrew-get-list-of-formulas-in-a-tap#25336816[Homebrew get list of formulas in a tap]


== perl

. cpan
. cpan App::cpanminus
. App::Asciio


== check these out

* Yazi
* Arai2
* FastFetch
* erdtree
* Dust
* tealdear

== Bookmarks for future projects

* https://github.com/eevee/rc/blob/master/.zshrc
* stderr in red https://stackoverflow.com/questions/6841143/how-to-set-font-color-for-stdout-and-stderr/21320645#21320645
* https://typer.tiangolo.com/ CLI apps, uses click,
* https://github.com/willmcgugan/rich rich text and colours in a terminal
* https://github.com/onelivesleft/PrettyErrors better looking stack traces
* https://github.com/marlonrichert/zsh-hist
* https://www.reddit.com/r/git/comments/ko3tnf/gitcompletion_13_released/ git-completion
* https://www.arp242.net/zshrc.html
* `defaults write com.apple.dock autohide-delay -float 0; killall Dock`
* `defaults write com.apple.dock autohide-time-modifier -float 0; killall Dock`
* `defaults write com.apple.dock no-bouncing -bool TRUE`; killall Dock  # stop the dock icons from bouncing when they want attention
* `defaults write com.apple.Dock appswitcher-all-displays -bool true` # app switcher on all displays https://gist.github.com/jthodge/c4ba15a78fb29671dfa072fe279355f0
* https://github.com/rxhanson/Rectangle
* https://github.com/sindresorhus/quick-look-plugins
* https://news.ycombinator.com/item?id=26499062 focalboard, self-hosted alternative to trello...
* https://github.com/plankanban/planka
* https://github.com/taigaio
* https://www.openproject.org
* https://github.com/GRVYDEV/Project-Lightspeed
* https://github.com/natethinks/jog/  remind me: what was I last doing in this directory
* https://github.com/vimpostor/vim-tpipeline put the vim status line into tmux's status line
* https://news.ycombinator.com/item?id=26314489 elegant bash conditionals, thread is more helpful than the post
* https://news.ycombinator.com/item?id=26303784 generate flowcharts from text, way more in the thread than I knew about
* https://github.com/crescentrose/dotfiles/blob/fed147052acb3a9249e0c5b5a042d97abcb70c55/bin/chtheme change kitty colors, maybe based on dark or light
* http://evantravers.com/articles/2019/07/30/toggling-kitty-and-neovim-background-using-osx-s-dark-mode-setting/  => https://github.com/evantravers/dotfiles/compare/084d4737b4dcdd0877520dcc1ba4e02224e4bdd0...2f5a3d18274499970922752d39fc917e4bf0d39b
* https://github.com/kovidgoyal/kitty/issues/1792
* zsh setopt SHARED_HISTORY and append_history, is SHARED_HISTORY why control+p shows things from a different session?
* https://www.reddit.com/r/selfhosted/comments/m9zhoy/what_are_some_lesser_known_services_that_have 
* https://venthur.de/2021-03-31-python-makefiles.html venv target should depend on requirements.txt and setup.py?
** not sure it adds anything beyond practicing salt
** https://github.com/remusao/salt-dotfiles
** https://github.com/robertu94/dotfiles
** https://www.reddit.com/r/saltstack/comments/li7g81/im_using_salt_to_manage_a_dotfiles_repo_with/
** https://github.com/rawkode/dotfiles
* https://serverfault.com/questions/174909/mount-block-file-on-osx[mount block file on macOS]

== Notes

=== ubuntu

. https://eza.rocks[eza]
. `apt install build-essential` for make and gcc
. `apt install fd-find` for fd  * DO NOT INSTALL `fdclone` *

=== Key Repeat Rate mac: macOS need restart

* more here: https://github.com/pctony/ConfigMyMac
* see also https://macos-defaults.com/#💻-list-of-commands

[source,shell]
----
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10
----

=== Linux Key Repeat Rate

[source,shell]
----
xset r rate 210 40
----


== Historical notes

* The powerline module gave me too much trouble, so I’m configuring that manually now, so I don’t need the python virtual environment anymore


.Default .zshrc ubuntu 22
[source,shell,linenums]
----
# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
----
