import = [
    "~/.config/alacritty/alacritty-theme/themes/papertheme.toml"
]

# others:
# papercolor_light.toml
# papertheme.toml



# [colors.primary]
# background = "#f5f5f5"
# foreground = "#444444"

[font]
size = 18

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[window]
# decorations = "none"
decorations = "full"
