[general]
live_config_reload = true
import = [
  "~/.config/alacritty/alacritty-theme/themes/papertheme.toml",
  "~/.config/alacritty/alacritty-theme/themes/papercolor_light.toml",
  "~/.config/alacritty/alacritty-theme/themes/papercolor_dark.toml",
  "~/.config/alacritty/alacritty-theme/themes/baitong.toml",
  "~/.config/alacritty/alacritty-theme/themes/blood_moon.toml",
  "~/.config/alacritty/alacritty-theme/themes/github_dark_high_contrast.toml",
  "~/.config/alacritty/alacritty-theme/themes/hyper.toml",
]

# others:
# moonfly
# papercolor_light.toml
# enfocado_dark
# papercolor_dark
# pastel_dark
# blood_moon
# nightowl
# nightfly
# kanagawa_dragon
# chicago95

# [colors.primary]
# foreground = "#a0a0a0"
# background = "#020202"


[font]
size = 12

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[window]
# decorations = "none"
decorations = "full"
# decorations_theme_variant = "Dark"
decorations_theme_variant = "None"
